---
title: "Join The Lab"
---

**THIS WEBSITE IS UNDER CONSTRUCTION AND THIS PAGE SHOULD NOT BE REFERENCED AT THIS MOMENT FOR OPEN POSITIONS IN THE LEVER LAB.**

**Postdoctoral Scholars**

The Lever Lab is currently hiring a postdoctoral scholar to develop Single-Particle Raman-Assisted Metagenomics (SPRAM) as a new tool that will enable scientists to integrate the fields of sedimentology, geochemistry, and microbiology and study the carbon cycle at the scale of single sedimentary particles. Applications will be reviewed starting July 15th, 2025.

Apply here: <https://utaustin.wd1.myworkdayjobs.com/en-US/UTstaff/job/PORT-ARANSAS-TX/Postdoctoral-Fellow_R_00039767>

**Research Staff**

The Lever Lab is currently not hiring for any research staff positions.

**Graduate Students**

Contact Dr. Lever via email with a brief description of your research interests and your CV prior to applying to the Marine Science MS or PhD program. The application deadline for Fall admissions is typically December 1st. More information about graduate study at UTMSI can be found here: <https://marinescience.utexas.edu/academics/graduate-programs>

Prospective graduate students are highly encouraged to apply for external funding, such as the [National Science Foundation Graduate Research Fellowships Program](https://www.nsfgrfp.org).

**Undergraduate Students**

UT Austin undergraduates may work on an independent research project with the Lever Lab through the Semester By The Sea program. More information about SBTS and other undergraduate programs at UTMSI can be found here: <https://marinescience.utexas.edu/academics/undergraduate-programs>
