---
title: "People"
---

# **Dr. Mark A. Lever**

**Principal Investigator**

2022-present: Associate Professor, University of Texas at Austin, Marine Science Institute

2014-present: Adjunct Professor, Aarhus University

2014-2022: Assistant Professor, ETH Zürich

2013-2014: Research Associate, Aarhus University

2009-2012: Postdoctoral Researcher, Aarhus University

2002-2008: PhD, University of North Carolina at Chapel Hill

1999-2002: MA, Boston University

1996-1999: BA, Boston University

```{=html}
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/gh/dheereshagrwal/coloured-icons@1.9.0/src/app/ci.min.css"
/>
<div class="social-icons">
        <a href="mailto:mark.lever@austin.utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
        <a href="https://orcid.org/0000-0002-2046-8028" target="_blank" rel="noopener noreferrer"><i class="ci ci-orcid ci-2x"></i></a>
        <a href="https://scholar.google.ch/citations?user=DG5WZZEAAAAJ&hl=en" target="_blank" rel="noopener noreferrer"><i class="ci ci-scholar ci-2x"></i></a>
      </div>
```

# **Daniel Hardin**

**Research Scientist Assistant**

2024-present: Research Scientist Assistant, University of Texas at Austin, Marine Science Institute

```{=html}
<div class="social-icons">
        <a href="mailto:daniel.hardin@austin.utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
      </div>
```

# **Kaitlyn Callagher**

**PhD Student**

[Research focus:]{.underline} Text

2023-present: PhD student, Marine Science, University of Texas at Austin, Marine Science Institute

```{=html}
<div class="social-icons">
        <a href="mailto:k.callagher@utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
      </div>
```

# **Claire White**

**MS Student**

[Research focus:]{.underline} Text

2024-present: MS student, Marine Science, University of Texas at Austin, Marine Science Institute

```{=html}
<div class="social-icons">
        <a href="mailto:claire.white@austin.utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
      </div>
```

# **John Hinkle**

**PhD Student**

[Research focus:]{.underline} Microbial ecology of abyssal sediments influenced by diffuse hydrothermal fluid flow

2024-present: PhD student, Marine Science, University of Texas at Austin, Marine Science Institute

2023-2024: Certificate, Applied Data Science, University of North Carolina at Chapel Hill

2020-2024: BS, Biology, University of North Carolina at Chapel Hill

```{=html}
<div class="social-icons">
        <a href="mailto:john.hinkle@utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
        <a href="https://www.linkedin.com/in/johnehinkle/" target="_blank" rel="noopener noreferrer"><i class="ci ci-linkedin ci-2x"></i></a>
        <a href="https://bsky.app/profile/johnehinkle.bsky.social" target="_blank" rel="noopener noreferrer"><i class="ci ci-bluesky ci-2x"></i></a>
        <a href="https://orcid.org/0000-0002-6381-4621" target="_blank" rel="noopener noreferrer"><i class="ci ci-orcid ci-2x"></i></a>
        <a href="https://scholar.google.com/citations?user=C_TSJ8AAAAAJ&hl=en&oi=ao" target="_blank" rel="noopener noreferrer"><i class="ci ci-scholar ci-2x"></i></a>
      </div>
```

# **Ariel Bellatin**

**Visiting Graduate Student** from the [Baker Lab](https://sites.utexas.edu/baker-lab/) at UT Austin

[Research focus:]{.underline} Microbial ecology of deep-sea sediments

2024-present: Graduate student, Marine Science, University of Texas at Austin, Marine Science Institute

2021-2024: Lab Manager, University of Texas at Austin

2017-2021: BS, Evolutionary Biology, Texas Tech University

```{=html}
<div class="social-icons">
        <a href="mailto:arielbellatin@utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
        <a href="www.linkedin.com/in/ariel-bellatin" target="_blank" rel="noopener noreferrer"><i class="ci ci-linkedin ci-2x"></i></a>
        <a href="https://orcid.org/0009-0002-2849-4957" target="_blank" rel="noopener noreferrer"><i class="ci ci-orcid ci-2x"></i></a>
      </div>
```

# **Sarah Vienna Gerlach**

**Undergraduate Student, Semester By The Sea**

[Research focus:]{.underline} Anaerobic microbial electron transfer methods and biogeochemistry

BS, Biology, University of Texas at Austin

```{=html}
<div class="social-icons">
        <a href="mailto:svgerlach@utexas.edu" rel="noopener noreferrer"><i class="ci ci-outlook ci-2x"></i></a>
        <a href="https://www.linkedin.com/in/sarah-v-gerlach/" target="_blank" rel="noopener noreferrer"><i class="ci ci-linkedin ci-2x"></i></a>
      </div>
```

# 
