---
title: "Research"
---

Research in the Lever Lab is driven by a common interest in in Earth’s carbon cycle. We pursue research questions of broad significance concerning the mechanistic and quantitative influence of microorganisms, humans, and abiotic factors on the short- and long-term fate of organic carbon in aquatic sediments and Earth’s crust. Currently, our research focuses on the following areas:

-   Influence of human societies on organic carbon sequestration in and greenhouse gas emissions from aquatic sediments.

-   Interactions between paleoenvironmental, sedimentological, geochemical and microbiological processes in controlling the long-term fate of organic carbon in marine sediments.

-   Deciphering anaerobic microbial food webs by linking organic carbon chemical compositions to the microorganisms and biochemical processes that transform them.

-   Role of macrobiota in driving carbon and nutrient cycling in marine and freshwater sediments.

-   Designing sustainable strategies (e.g., seaweed farming) to enhance the burial of atmospheric carbon dioxide in aquatic sediments and reduce greenhouse gas emissions.

-   Importance of tectonic processes and deep mantle-derived energy sources in sustaining subseafloor life.
